#!/usr/bin/env python3
"""Wave12: learned joint ticket-value policy for v288 final NO_BET add-ons.

For every candidate race, evaluate the frozen pre-race ticket matrix (Top2..Top10 and
composite-odds targets) and learn expected settled value jointly from race features plus
ticket descriptors. Every test month is trained on prior months only. The policy chooses
at most one ticket structure per race and uses the exact historical 10,000-yen Dutch
settlement already regenerated by Wave2. September outcomes are forbidden.
"""
from pathlib import Path
import json, os
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.impute import SimpleImputer
from sklearn.pipeline import make_pipeline
import research_v289_3head_addon as w1
import research_v289_3head_addon_wave2 as w2

OUT_JSON=Path('research_v289_3head_addon_wave12_joint_ticket_value.json')
OUT_MD=Path('research_v289_3head_addon_wave12_joint_ticket_value.md')
BANK=10000
FRACTIONS=(.15,.25,.40)
TOPK=18

def select_features(tr_race, cols):
    # Rank features against the best realized ticket value per prior race only.
    best=tr_race.groupby('race_code',as_index=False).ret_alt.max().rename(columns={'ret_alt':'best_ret'})
    base=tr_race.drop_duplicates('race_code')[['race_code']+cols].merge(best,on='race_code',how='inner')
    y=np.log1p(pd.to_numeric(base.best_ret,errors='coerce').fillna(0)/BANK)
    rows=[]
    for c in cols:
        x=pd.to_numeric(base[c],errors='coerce'); ok=x.notna()&np.isfinite(x)&np.isfinite(y)
        if ok.sum()<30 or x[ok].std()<=1e-12: continue
        r=np.corrcoef(x[ok],y[ok])[0,1]
        if np.isfinite(r): rows.append((abs(r),c))
    return [c for _,c in sorted(rows,reverse=True)[:TOPK]]

def metric_ticket(df):
    n=len(df); payout=float(pd.to_numeric(df.ret_alt,errors='coerce').fillna(0).sum()) if n else 0.0
    hits=int(pd.to_numeric(df.hit_alt,errors='coerce').fillna(0).sum()) if n else 0; stake=n*BANK
    return {'races':int(n),'hits':hits,'hit_rate_pct':100*hits/n if n else None,'stake_yen':stake,'payout_yen':payout,'profit_yen':payout-stake,'roi_pct':100*payout/stake if stake else None}

def maxdd_ticket(df):
    if len(df)==0:return 0.0
    z=df.sort_values(['date','race_code']); pnl=pd.to_numeric(z.ret_alt,errors='coerce').fillna(0)-BANK
    curve=pnl.cumsum().to_numpy(float); peaks=np.maximum.accumulate(np.r_[0.,curve]); return float((peaks[1:]-curve).max())

def monthly(g):
    d={m:metric_ticket(x) for m,x in g.groupby('month')}; r=[x['roi_pct'] for x in d.values() if x['roi_pct'] is not None]
    return d,sum(x<100 for x in r),min(r) if r else None

def build_matrix(q, raw, candidate_codes):
    mat,_=w2.regenerate(q.race_code.astype(str))
    mat['race_code']=mat.race_code.astype(str)
    # attach only pre-race safe race features; matrix settlement fields stay target only
    featcols=w1.safe_live_cols(raw)
    featcols=[c for c in featcols if c in raw.columns and c not in ('p3',)]
    race=raw[['race_code','month','raw_route']+featcols].copy(); race['race_code']=race.race_code.astype(str)
    race=race.drop_duplicates('race_code')
    mat=mat.merge(race,on=['race_code','month'],how='left')
    mat['is_candidate']=mat.race_code.isin(set(candidate_codes))
    return mat,featcols

def main():
    q,baseline,candidates,raw=w2.base_universe()
    if q.date.max()>'2026-08-31': raise RuntimeError('September forbidden')
    candcodes=set(candidates.race_code.astype(str)); mat,allcols=build_matrix(q,raw,candcodes)
    # Training universe: all prior v288 final NO_BET races for which ticket alternatives were regenerated.
    trainmat=mat[mat.raw_route=='NO_BET'].copy()
    choices=[]; audit={}
    months=sorted(candidates.month.unique())
    for m in months:
        tr=trainmat[trainmat.month<m].copy(); te=mat[(mat.month==m)&mat.is_candidate].copy()
        audit[m]={'train_ticket_rows':int(len(tr)),'train_races':int(tr.race_code.nunique()),'test_ticket_rows':int(len(te)),'test_races':int(te.race_code.nunique())}
        if tr.race_code.nunique()<30 or te.empty: continue
        fs=select_features(tr,allcols); audit[m]['features']=fs
        if len(fs)<5: continue
        # Each candidate ticket option is one supervised row. Ticket descriptors are available pre-race.
        modelcols=fs+['n_alt','comp_alt']
        Xtr=tr[modelcols].apply(pd.to_numeric,errors='coerce')
        y=np.log1p(pd.to_numeric(tr.ret_alt,errors='coerce').fillna(0)/BANK)
        model=make_pipeline(SimpleImputer(strategy='median'),RandomForestRegressor(n_estimators=240,max_depth=5,min_samples_leaf=8,max_features=.7,random_state=20260913,n_jobs=-1))
        model.fit(Xtr,y)
        # Fail closed on required current race features; ticket descriptors also must exist.
        Xte=te[modelcols].apply(pd.to_numeric,errors='coerce'); valid=Xte.notna().all(axis=1)
        te=te.loc[valid].copy(); audit[m]['valid_ticket_rows']=int(len(te)); audit[m]['valid_races']=int(te.race_code.nunique())
        if te.empty: continue
        te['_pred']=model.predict(te[modelcols].apply(pd.to_numeric,errors='coerce'))
        # One ticket structure per race = joint race/config argmax.
        bestte=te.sort_values(['race_code','_pred'],ascending=[True,False]).groupby('race_code',as_index=False).head(1).copy()
        # Prior predicted maxima define a policy threshold without current-month outcomes.
        predtr=pd.Series(model.predict(Xtr),index=tr.index); t2=tr.copy(); t2['_pred']=predtr
        besttr=t2.sort_values(['race_code','_pred'],ascending=[True,False]).groupby('race_code',as_index=False).head(1)
        for frac in FRACTIONS:
            cutoff=float(besttr._pred.quantile(1-frac)); g=bestte[bestte._pred>=cutoff].copy(); g['_fraction']=frac; choices.append(g)
    rows=[]; detail={}
    for frac in FRACTIONS:
        parts=[x for x in choices if len(x) and float(x['_fraction'].iloc[0])==frac]
        g=pd.concat(parts,ignore_index=True) if parts else mat.iloc[0:0].copy()
        a=metric_ticket(g); a['max_drawdown_yen']=maxdd_ticket(g); mo,red,mn=monthly(g)
        # baseline has canonical ret/hit columns; normalize to ticket metric schema
        b=baseline[['date','race_code','ret','trifecta_hit']].copy(); b['month']=b.date.astype(str).str[:7]; b=b.rename(columns={'ret':'ret_alt','trifecta_hit':'hit_alt'})
        comb=pd.concat([b,g[['date','race_code','month','ret_alt','hit_alt']]],ignore_index=True); cm=metric_ticket(comb); cm['max_drawdown_yen']=maxdd_ticket(comb)
        row={'method':'joint_ticket_value_rf','fraction':frac,'addon':a,'monthly':mo,'red_months':red,'min_monthly_roi_pct':mn,'combined':cm,'overlap_with_v288':0,'config_counts':g.config.value_counts().to_dict() if len(g) else {}}
        rows.append(row); detail[f'joint_ticket_value_rf@{frac:.2f}']=g[['date','race_code','month','config','n_alt','comp_alt','hit_alt','ret_alt','_pred']].to_dict('records') if len(g) else []
    rows.sort(key=lambda x:((x['addon']['roi_pct'] or -1),x['addon']['races']),reverse=True)
    passers=[x for x in rows if x['addon']['races']>=20 and (x['addon']['roi_pct'] or 0)>=100 and (x['min_monthly_roi_pct'] or 0)>=60 and x['red_months']<=3]
    dec='SHADOW_CANDIDATE_WAVE12' if passers else 'NO_ADOPTION_WAVE12'
    bm=w1.metric(baseline); out={'research_version':'v289-addon-wave12-joint-ticket-value','github_run_id':os.getenv('GITHUB_RUN_ID'),'source_max_date':q.date.max(),'rules':{'baseline_fixed':'v288 94R','candidate':'final v288 NO_BET only','mechanism':'joint race+ticket expected settled value; one config per race','ticket_family':'Wave2 regenerated Top2..Top10 + target composite odds; exact 10000-yen Dutch','test':'walk-forward Feb-Aug','training':'prior-month final-NO_BET ticket rows only','current_required_missing':'FAIL_CLOSED','july_august':'NON-PRISTINE','september_outcomes_used':False},'baseline':{**bm,'max_drawdown_yen':w1.max_drawdown(baseline)},'candidate_pool':w1.metric(candidates),'methods':rows,'passers':passers,'decision':dec,'audit':audit,'detail':detail}
    OUT_JSON.write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    L=['# v289 3号艇 add-on — Wave 12 joint ticket-value policy','', '- v288 **94R fixed**, final NO_BET only','- learned race+ticket expected value across Top2..Top10 / target-composite-odds configurations','- chooses at most one exact-10,000-yen-Dutch ticket structure per race','- prior-month-only walk-forward Feb-Aug; current required feature missing => fail closed','- Jul/Aug NON-PRISTINE; September outcomes unused','', '## Methods','|method|frac|R|hits|hit rate|ROI|profit|min month|red|max DD|overlap|combined R|combined ROI|','|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|']
    for x in rows:
        a=x['addon']; c=x['combined']; mn=x['min_monthly_roi_pct']
        L.append(f'|{x["method"]}|{x["fraction"]:.2f}|{a["races"]}|{a["hits"]}|{a["hit_rate_pct"] if a["hit_rate_pct"] is not None else float("nan"):.2f}%|{a["roi_pct"] if a["roi_pct"] is not None else float("nan"):.2f}%|{a["profit_yen"]:+,.0f}|{mn if mn is not None else float("nan"):.2f}%|{x["red_months"]}|{a["max_drawdown_yen"]:,.0f}|0|{c["races"]}|{c["roi_pct"]:.2f}%|')
    L += ['', '## Decision',f'**{dec}**']
    OUT_MD.write_text('\n'.join(L)+'\n',encoding='utf-8'); print('\n'.join(L)); print('V289_WAVE12_JOINT_TICKET_VALUE_OK')
if __name__=='__main__': main()
